version: '3.9'

services:
  todo-app:
    container_name: todo-app 
    image: postrgresslearn/todo-app
    ports:
      - 5000:5000
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - DATABASE_CONNECTION_STRING=host=postgres user=todo password=pass dbname=todo port=5432 sslmode=disable


  postgres:
    container_name: todo-postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=todo
      - POSTGRES_DB=todo

